### ISSUE TITLE
WaarOverheid location data integration

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#125]
The [WaarOverheid.nl](https://waaroverheid.nl/) service is a web application that extracts location data from ORI texts using [LocLinkVis](https://arxiv.org/abs/1509.02010). The [back-end](https://github.com/WaarOverheid/open-raadsinformatie) is a fork of the v0 ORI API.

Our goal is to include the location data in the ORI API. The [WaarOverheid front-end application](https://github.com/stamkracht/waaroverheid) should use this API as well.

**Comment by jorritb** [comment]
We decided to try to implement LocLinkVis as its own service in the ORI architecture instead of using the WaarOverheid backend. The location data can be added using an enricher.

**Comment by jurrian** [comment]
I've already got a basic setup for the WaarOverheid enricher that you can use.

**Comment by joepio** [comment]
When adding this data to Elasticsearch, use [Geo-Points](https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html). If we use this, we can use some cool map features in the ori-search app.

**Comment by joepio** [comment]
It might be easier to not store the geo data itself in ES / ORI, only references to locations. The location data would reside in LocLinkVis. This might make it a lot easier to implement.

However, this also means that users will need to query both services in order to show location data on a map. It also means that we can't use ElasticSearch's Geo query featuers, which means that we can's use a [map + radius filter](https://opensource.appbase.io/playground/?path=/story/map-components-geodistanceslider--with-range-labels) in ori-search.

**Comment by aolieman** [comment]
All of WaarOverheid's "location data" resides in LocLinkVis. Stated the other way around: no coordinate pairs are stored in the forked ORI v0 Elasticsearch. This is an intentional separation of concerns, requiring minimal adaptations to the ORI codebase. Our aim here was to modify the ORI codebase as little as possible to make upstreaming easier.

> However, this also means that users will need to query both services in order to show location data on a map.

Indeed, if you mean to show shapes plus document counts on a map -- like the WaarOverheid app does -- that requires the location data from LocLinkVis and the hit counts from Elasticsearch. I think this is reasonable, but can be made to look a bit nicer with a reverse proxy:

https://api.waaroverheid.nl/municipal/GM0518/districts
https://api.waaroverheid.nl/municipal/GM0518/adjacent
https://api.waaroverheid.nl/v0/gm0518/search

Loading the location data into Elasticsearch as well sounds really cool to me, but I would suggest saving that for a later milestone. As long as you plan to use LLV to generate the location annotations for documents, you might as well let it serve some GeoJSON, right? ;-)

**Comment by jurrian** [comment]
Has been implemented in v1.5.0
