### ISSUE TITLE
Implement SearchGuard

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#143]
Having an ES endpoint is highly valuable for many who want to use ORI data. Unfortunately, it comes at a cost: open endpoints means that anybody can write data... That's not good.
We currently use Google Endpoints to only allow certain endpoints, but this does not work with all clients. Some Python ES libraries need many endpoints. To fix this, we could use the proprietary Elastic Security solution. However, this is quite costly. Fortunately, there is an open source alternative: [SearchGuard](https://docs.search-guard.com/latest/search-guard-community-edition). Let's try that one.

**Comment by jurrian** [comment]
We decided that SearchGuard might be a bit overkill here since TLS between nodes is mandatory, it's very strict about that. TLS between local nodes might be a smart thing for protecting sensible (enterprise) data on the local network, however for this project there might be considerable overhead in making this work. For now Google Endpoints service will shield the endpoints for third party consumer use. We will still need to find an admin and special use endpoint which needs some appropriate measure of protection.
