### ISSUE TITLE
Enable date filtering on all resources in Elastic

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#181]
Many resources lack relevant date fields. In the [ori-search](https://github.com/ontola/ori-search) app, I'd like to show a `dateRange` slider that helps users to find items that were mentioned in a certain time frame.

Since the domain of this application is meetings, and all meeting resource (Motions, Documents, Etc.) are discussed in a certain meeting, I suggest that we provide all relevant resources with a `meeting:firstAppearedAt` attribute. This is especially relevant for Attachments / MediaObjects PDF files.

However, this feels a bit dirty, because this would mean that information that is actually present in a Meeting will be duplicated to some other Resource. Ideally, this would be fixed by using the right query, but I can't see how we could fix this without relying on SPARQL or something.

**Comment by fletcher91** [comment]
> I suggest that we provide all relevant resources with a meeting:firstAppearedAt attribute

This can be done in elastic separately so it shows up in the results. No need to pollute the actual resources with search related implementation details

**Comment by jurrian** [comment]
So to clarify, we add the extra field only to the sub-resources in elastic. The API service will have no such field and will in this way contain only primary data. Secondary data, like this derived field can be added to elastic to enhance the applications that will use the data. This does create a discrepancy between the elastic and API service, but as we see it now this is not necessarily a problem since elastic and API are not designed serve exactly the same. However, the discrepancy could cause confusion so we probably should find some way to communicate the difference or document is somewhere.

**Comment by jorritb** [comment]
Documents can be discussed at more than one meeting. Since meetings are extracted chronologically with the most recent meetings being processed last, `lastAppearedAt` would be more appropriate because extracting a more recent meeting will overwrite the date with the more recent meeting's date.

**Comment by joepio** [comment]
That might be easier to implement, but it might be less relevant (depending on who's doing the query). However, since I've yet to see a single document that is used in two seperate documents, it's fine by me.

**Comment by jorritb** [comment]
`lastDiscussedAt` has been implemented for agenda items and attachments. All meetings, agenda items and attachments should now have a relevant date field.

**Comment by breyten** [comment]
Nice, thanks!
