### ISSUE TITLE
More efficient loader behaviour

### ISSUE THREAD

**Issue by jurrian** [openstate/open-raadsinformatie#186]
Currently we use `traverse()` in the loaders to load every leaf in the object tree to a store. For elasticsearch we use the UpsertLoader to merge the attributes of the objects A and B. This is needed if B contains additional attributes to A. However, this behaviour is not very efficient since in most cases the data is exactly the same. Could we find a more efficient way to reduce the number of unnecessary requests to the store? Perhaps we can compare for differences before doing a request.

**Comment by jurrian** [comment]
For example, the last id (local) is repeated multiple times, probably without being changed.
```
[elasticsearch] DEBUG ElasticsearchUpsertLoader indexing document id: https://id.openraadsinformatie.nl/8212
[elasticsearch] DEBUG ElasticsearchUpsertLoader indexing document id: https://id.openraadsinformatie.nl/8213
[elasticsearch] DEBUG ElasticsearchUpsertLoader indexing document id: https://id.openraadsinformatie.nl/8211
[elasticsearch] DEBUG ElasticsearchUpsertLoader indexing document id: https://id.openraadsinformatie.nl/8210
[elasticsearch] DEBUG ElasticsearchUpsertLoader indexing document id: https://id.openraadsinformatie.nl/8210
[elasticsearch] DEBUG ElasticsearchUpsertLoader indexing document id: https://id.openraadsinformatie.nl/8210
[elasticsearch] DEBUG ElasticsearchUpsertLoader indexing document id: https://id.openraadsinformatie.nl/8210
[elasticsearch] DEBUG ElasticsearchUpsertLoader indexing document id: https://id.openraadsinformatie.nl/8210
[elasticsearch] DEBUG ElasticsearchUpsertLoader indexing document id: https://id.openraadsinformatie.nl/8210
```

**Comment by jurrian** [comment]
It is inefficient to the extend that more than 24 hours of processing resulted in about 25 new resources. It seems to process the same resources over and over again.

**Comment by jorritb** [comment]
The only way to make this more efficient that I can currently think of is to pass a parameter to the model constructor which indicates that the resource should not be re-loaded. 

For example: when you assign a meeting to a municipality with `has_organization_name` the municipality does not need to be re-loaded because it almost certainly already exists.

But this would mean that we would have to bring back the extraction hierarchy of municipality/province > committees > organizations > persons > meetings, which is something we have been moving away from on purpose to be more flexible.

Any other ideas are welcome.
