### ISSUE TITLE
Slow enricher tasks

### ISSUE THREAD

**Issue by jurrian** [openstate/open-raadsinformatie#204]
There are currently some enricher tasks which take about 3,5 hours to process, these extreme long processes are clogging up the ETL system. These tasks need to be identified, analysed to see what takes so long and solved. There is a good chance that the processing of hundreds or more PDF's could be the issue here. If that is the case we need to adopt a strategy to cope with that problem. Since it is clogging the ETL system we will give this high priority.

**Comment by jorritb** [comment]
Since enrichment tasks are very expensive it would make sense to track which resources have already been enriched and skip those on the next pass.

I suggest implementing an Enricher Log that keeps track of resource id, enricher task type and enrichment date and skips the enricher task if it is already in the enrichment log.

**Comment by jorritb** [comment]
The Enricher Log has been implemented, so moving this to a different milestone.

**Comment by jurrian** [comment]
Extracting text from hundreds of thousands of PDFs totalling up to more than 150 GB has proved to slow things down considerably, 20 pages can take several minutes. Currently the extraction is done over and over again without good strategy. PDFs will now be extracted just once and cached on Google Cloud Storage. To speed things up further we will dedicate a large amount of cloud resources the coming weeks to preemptively extract everything we currently have to prefill the cache. This should smooth things in the ETL system.
