### ISSUE TITLE
Details of organizations are missing in linked data output

### ISSUE THREAD

**Issue by breyten** [openstate/open-raadsinformatie#207]
Compare 

https://id.openraadsinformatie.nl/93.jsonld

Versus

https://api.openraadsinformatie.nl/v1/elastic/_search?q=_id:93&pretty

Why is that? (I guess this is not supposed to be happining? or is this becuase of 1.3?)

**Comment by joepio** [comment]
Might be related to the fact that the loader for ori_api replaces resources, while elastic appends (upserts?).

Also, related to #180

**Comment by jorritb** [comment]
@fletcher91 does the ori api perform upserts or does it just replace an entire resource? If that's the case then you're going to be missing a lot of information.

**Comment by breyten** [comment]
I suppose that would make sense :)

**Comment by fletcher91** [comment]
@jorritb The [supplant](https://www.merriam-webster.com/dictionary/supplant) graph replaces them entirely, which is the expected behaviour.

So a different graph IRI should be used to convey the proper meaning of how the deltas are processed. The corresponding IRI might already be defined, though some implementation details with regards to elastic could cause issues.

We're going to try to implement a hotfix before the weekend, but in the end, the delta loader should update its behaviour to supply the _entire_ representation of the resource, or use the appropriate graph for the intended operation.

**Comment by joepio** [comment]
Related: https://github.com/ontola/ori_api/issues/3

**Comment by joepio** [comment]
If I understand correctly, the problem is that ORI incorrectly sends Linked-Deltas to the ori_api kafka bus with a linked-delta:suppland quad, which replaces the entire organisation, but it should be :replace

**Comment by jurrian** [comment]
It looks like the problem has been solved. replace is now being used in favor of supplant in ori_api. The initial item looks good to me now.
