### ISSUE TITLE
Check that public documents from iBabs are included which are not accessible by public account.

### ISSUE THREAD

**Issue by monty241** [openstate/open-raadsinformatie#220]
See picture. It seems that at least one municipality might have public documents that should be in openraadsinformatie but that are not made available through the public iBabs account.

When iBabs site Harderwijk was HTML scraped the document "Faillissement WZCO en vervolg" was not found. Also, a Google search on the materialized scrape results on "filetype:pdf site:hierden-bosch.nl "Faillissement WZCO"" returns no hits.

Since Harderwijk is not accessible yet: please check after adding it that this document is included.

When not:
- check in municipalities that credentials with sufficient privileges are used.
- maybe it is a good idea to add an application control that public documents are available by the API, such as cross-checking between scraping and API results.

**Comment by monty241** [comment]
![image](https://user-images.githubusercontent.com/7579444/63484978-e73faf00-c4a1-11e9-8f4a-2bdd62e3362e.png)

**Comment by jurrian** [comment]
Given that I don't know enough about the referenced document, I cannot tell if we have access to it. If we do have access it should have been indexed (or might be indexed in the future). There is a fair chance that iBabs won't show it to us as it might be classified. At the moment these are the only documents related to what you are looking for: https://ori.argu.co/search?zoekterm=%22WZCO%22&datums=%5B1517439600000%2C1569853896866%5D&organisaties=%5B%22ori_harderwijk_20190809125106%22%5D

I am closing this for now, since I have no idea what role we can play. Feel free to comment.

**Comment by monty241** [comment]
Yes, it is a hard one. Better to first make sure that all known documents reliably land using some kind of application control but that often requires help from the data suppliers.
