### ISSUE TITLE
MediaObjects do not always have a url field

### ISSUE THREAD

**Issue by breyten** [openstate/open-raadsinformatie#263]
See [this link](https://api.openraadsinformatie.nl/v1/elastic/_search?q=_id:99212)

![image](https://user-images.githubusercontent.com/154791/65607408-cb519080-dfac-11e9-9f0f-2c013f84f2d5.png)

**Comment by joepio** [comment]
Why is this a bug?

The JSON is still valid, and it [parses correctly as JSON-LD](https://json-ld.org/playground/#startTab=tab-nquads&json-ld=%7B%22has_organization_name%22%3A%2252%22%2C%22name%22%3A%22Ontwerp%20Begroting%202020%20Plassenschap%20Loosdrecht%20e.o..pdf%22%2C%22original_url%22%3A%22https%3A%2F%2Fapi1.ibabs.eu%2Fpublicdownload.aspx%3Fsite%3DNoordHolland%26id%3Dc23805d0-4c12-4488-87d0-fd7b58d16535%22%2C%22size_in_bytes%22%3A737376%2C%22last_discussed_at%22%3A%222019-09-30T00%3A00%3A00%2B00%3A00%22%2C%22isReferencedBy%22%3A%2298893%22%2C%22%40context%22%3A%7B%22has_organization_name%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fwww.w3.org%2F2006%2Fvcard%2Fns%23hasOrganizationName%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22name%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fschema.org%2Fname%22%7D%2C%22original_url%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fschema.org%2FisBasedOn%22%7D%2C%22size_in_bytes%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fschema.org%2FfileSize%22%7D%2C%22last_discussed_at%22%3A%7B%22%40id%22%3A%22https%3A%2F%2Fargu.co%2Fns%2Fmeeting%2FlastDiscussedAt%22%7D%2C%22%40base%22%3A%22https%3A%2F%2Fid.openraadsinformatie.nl%2F%22%2C%22isReferencedBy%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2FisReferencedBy%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22MediaObject%22%3A%22http%3A%2F%2Fschema.org%2FMediaObject%22%7D%2C%22%40id%22%3A%2299212%22%2C%22%40type%22%3A%22MediaObject%22%7D&context=%7B%7D). This is due to the `@context` object, where the `MediaObject` string is mapped to a URL.

**Comment by jurrian** [comment]
This happens when the MediaEnricher has not been run (or failed). For such problems it's hard to trace back what happened. It could be that the problem solves itself when the items are revisited. If that does not happen I will try to investigate if there is more to it.

**Comment by jurrian** [comment]
It seems the mentioned MediaObject has been reprocessed and now has an url and text.
