### ISSUE TITLE
Missing items in ID API - delta's not put on kafka bus?

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#285]
When opening most of the [2018](https://ori.argu.co/?zoekterm="2018"&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F268308&datums=%5B1517439600000%2C1545278846367%5D) resources, the titles and attributes between the Elastic and REST items mismatch, or 404. Also, some resources link to nonsensical other resources (e.g. [this](https://id.openraadsinformatie.nl/266750.ttl) person links to a document as its parent organisation, and [this](https://id.openraadsinformatie.nl/278423.ttl) creativework has a parent organisation that is an AgendaItem).

Similar issues have happened before. I think we have basically two approaches: either we find the cause of this problem (probably simpler), or we switch to the [elastic-delta-loader](https://github.com/ontola/elastic-delta-loader) (more long-term, fundamental solution).

**Comment by joepio** [comment]
Possible cause: `ori_api` has old data (since the mentioned mismatched identifiers use the `argu.co` namespace, which was deprecated some months ago), and is not correctly overwritten by new delta's.

**Comment by jurrian** [comment]
The 'creative work' mentioned above (278423) is a MediaObject in Elastic as well as Postgres so it suggests that ORI API is lagging behind. ORI API has been crashing a lot lately, first thing is to try to fix that to see if processing resumes normally. Although I am a bit worried that the `replace` behaviour in ORI API will replace changed or new attributes but will keep the old ones, mixing the resource up. The reprocessor that is being developed in #277 will enable us to use `supplant` to extract everything from the database and reprocess it correctly to ORI API again.

**Comment by fletcher91** [comment]
Trying new patches

**Comment by joepio** [comment]
Seems to be working - over 90% of 2018 links [seem](https://ori.argu.co/?zoekterm=%22wat%22&datums=%5B1517439600000%2C1543303715543%5D&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F396772) to be correct now.

**Comment by jurrian** [comment]
The manual reprocessing of the ORI API seems to have worked. The resources that initially failed are now MediaObjects. On small thing though, since ORI API uses `replace` instead of `supplant`, some attributes like `prov:hadPrimarySource` have remained on the resource. This effectually pollutes the resources with wrong data and must be fixed by total reprocessing. Closing this for now.

**Comment by joepio** [comment]
The patch seems not to work for items that were imported in the next batch (2000 - 2017).

**Comment by fletcher91** [comment]
Resources which still 404 seem to have never been put on the bus, so perhaps a loader problem?

**Comment by joepio** [comment]
@jorritb will try if re-running helps to resolve the issues. We'll re-run 2017-02.

Some identifiers that currently 404:

https://id.openraadsinformatie.nl/989925
https://id.openraadsinformatie.nl/989924
https://id.openraadsinformatie.nl/989918
https://id.openraadsinformatie.nl/989917
https://id.openraadsinformatie.nl/828670
https://id.openraadsinformatie.nl/715868

[Browse in this daterange in search](https://ori.argu.co/?zoekterm=%22*%22&datums=%5B1485907200000%2C1488326400000%5D&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F715868&organisaties=%5B%22osi_noord-holland_20190809125038%22%5D)

**Comment by joepio** [comment]
Run succeeded without errors, but resources still 404...

**Comment by jorritb** [comment]
I think I've found the problem:

https://github.com/openstate/open-raadsinformatie/blob/5d93507f64a42459e37a7945147232c3985f2fca/ocd_backend/loaders/delta.py#L32

`KAFKA_HOST` and `KAFKA_PORT` are both required for the DeltaLoader to run, but in the backend container `KAFKA_PORT` is not set (because the port is part of the host string), so the DeltaLoader doesn't run.

**Comment by jorritb** [comment]
The resources are coming through now. We will still have to re-do 2010-2018 (except February 2017).

**Comment by jurrian** [comment]
We have discovered that the disk space on the `ori_api` service has been sufficient but the 30M available inodes have run out. To try to mitigate this in the future we now run a daily cleanup script that should free inodes.

As a result resources have not been processed for some weeks which could explain the missing resources. The kafka offset has been reset to the date of 28-11-2019, we expect that when this all has been reprocessed the results should be much better.

**Comment by joepio** [comment]
After reprocessing all the data, about 40% is still 404ing. This is better than before, but still far from required.

**Comment by fletcher91** [comment]
Inodes seem to be the problem, investigating solutions.

**Comment by jurrian** [comment]
I have checked the python backend logs and sampled 11 resources that are missing in the ori api. 2 of the 11 seems not to be delivered which *could* be due to problems like #267. 8 of the 11 seem to be delivered to Kafka and appear in the ori api processing logs. On closer inspection on one resource it seems that inodes are **again** the problem. The daily cleanup script has not been enough, so we are trying solutions now to solve this inode problem once and for all.

**Comment by jurrian** [comment]
With more inodes being allocated and Kafka replayed from 29-11-2019 the problem has been reduced. Most of the resources in this issue are now as they should be. A script has been created to be able to sample resources, #310 will track progress in making the API service more complete. This issue will be closed in favor of that one.
