### ISSUE TITLE
Add versioning / deprecation strategy

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#302]
Having a solid strategy for dealing with API versions can help developers properly use our API. As more organizations rely on open raadsinformatie, it becomes more important to have one.

I spoke to @bwbroersma about API versioning and deprecation notices. He had some interesting ideas on this, all implemented in [this folder](https://github.com/openstate/allmanak/tree/master/nginx/shared), using deprecation headers like this:

```nginx
add_header Deprecation 'version="v0", date="Tue, 23 Jul 2019 23:59:59 GMT"';
add_header Sunset 'Fri, 31 Jan 2020 23:59:59 GMT';
add_header Link '<https://rest-api.allmanak.nl/v1/>; rel="successor-version"';
add_header Link '<https://www.allmanak.nl/api/#policy>; rel="deprecation"';
``` 

I think we should do something similar. 

- [ ] Mention deprecation strategy in docs

**Comment by bwbroersma** [comment]
Also note https://www.allmanak.nl/api/#policy with the HTTP Status. There is a reasoning behind going from `200 OK` to `207 Multi-Status` to `301 Moved Permanently` and finally `410 Gone`. It's inspired on the multiple answers on the StackOverflow question [Convention for HTTP response header to notify clients of deprecated API](https://stackoverflow.com/q/13884141/589293).
First X months, do nothing except extra (RFC) headers, and you could actively notify API users if they use a User-Agent with contact information, e.g. `Mozilla/5.0 (compatible; AppName/1.0; +https://link-to-the-app/)`, then the `207` will make clients that checking on a `200` code fail, but it should be easy to temporarily fix. Then `301` will make more clients fail (since follow redirects is not always enabled), but again easy to migrate from. Finally we will have to deprecate the API by marking it `410` Gone.

**Comment by joepio** [comment]
Deprecation strategy added: https://github.com/openstate/open-raadsinformatie/wiki/Open-Raadsinformatie-API-docs#api-versioning--deprecation

No HTTP statuses yet, since we think it might be easier for developers to be notified by mail, than requiring them to write notification logic in client applications.

In the future, we should consider implementing the machine-readable suggestions from BWB as well - especially when the amount of API users grows. Closing this for now.
