### ISSUE TITLE
Some PDF documents not being imported

### ISSUE THREAD

**Issue by joepsz** [openstate/open-raadsinformatie#32]
For example [this meeting](http://api.openraadsinformatie.nl/v0/doetinchem/events/41cd98ee5fd13729f7247eef86cd1e758bb0e25a) includes only 3 documents, whilst [its source](https://besluitvorming.doetinchem.nl/api/v1/meetings/6737) includes 5. Perhaps there is something different about the two missing documents ([1](https://besluitvorming.doetinchem.nl/api/v1/meetings/6737/documents/23620), [2](https://besluitvorming.doetinchem.nl/api/v1/meetings/6737/documents/23621)) in this example. This issue might be fixed with the [new PDF parser](https://github.com/openstate/open-raadsinformatie/commits/pdfparser).

**Comment by breyten** [comment]
Hopefully! PDF miner something has trouble reading big & complicated pdfs (which tends to happen when maps are included), so that might be one reason. The other might be that the pdf specifies that the text cannot be copied (which pdf minder respects).

Anyway, I'll be testing the new pdf parser shortly.

**Comment by joepsz** [comment]
Just ran the most recent master locally and got all 5 documents. So perhaps something is going wrong in a later stage?

**Comment by breyten** [comment]
Yay for HTTP errors? ;)

**Comment by jurrian** [comment]
I guess this issue is resolved by the new PDF parser and additionally the Tika parser for documents other than PDF, closing this for now.
