### ISSUE TITLE
Add @context for linked-data definitions

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#34]
Having an `@context` prop at the top of every JSON response in the API makes the API more self-explanatory. Every single attribute (e.g. `title` or `start_date`) will have a link to its definition, which helps developers anticipate on the kind of data that they shall receive and how to interpret that data. Since this project already uses the international Popolo standard, I'd suggest we just copy the context files that they already have added (e.g. [this one for `vote_events`](http://www.popoloproject.com/specs/vote-event.html#vote-event-context)).

**Comment by breyten** [comment]
Yup, that would be great

**Comment by joepsz** [comment]
We could add a JSON-LD mapping in at least two ways. One is adding an `@context` object in each response. The other is to [add a link header that describes the mapping](http://json-ld.org/spec/latest/json-ld/#interpreting-json-as-json-ld), which is a bit easier but perhaps less obvious to developers.

It seems that Popolo has already created [some](www.popoloproject.com/contexts/speech.jsonld) JSON-LD files. We'll use these.

**Comment by joepsz** [comment]
I created a [Popolo ontology](https://github.com/joepsz/popolo-spec/blob/ontology/ontology.owl) and generated a [JSON-LD context file](https://github.com/joepsz/popolo-spec/blob/ontology/context.jsonld) from that ontology. 

We could use this to improve the ORI API, so it could be interpreted by LD software and therefore automatically be converted to an RDF graph.

However, the current API has conflicting / inconsistent property names, since [popolo has the same problem](https://github.com/popolo-project/popolo-spec/issues/127). For example, the 'parent' attribute [refers to a schema:superEvent in events](http://www.popoloproject.com/contexts/event.jsonld), but it refers to an [organization in the organization context](http://www.popoloproject.com/contexts/organization.jsonld). 

I suggest that for the next version of the ORI api, we change the property names to the ones from the generated context file. This prevents conflicts.

**Comment by jurrian** [comment]
I've started implementing `@context` for each nested resource. For example, a nested membership resource will have it's own context. This way no conflicts will arise.

**Comment by jurrian** [comment]
This is now fixed in V1.
