### ISSUE TITLE
Update_source not matching scenario 2

### ISSUE THREAD

**Issue by jurrian** [openstate/open-raadsinformatie#357]
## Error in ori

**LogWARNING** in **models/postgres_database.py:321**
Unable to update source: No matching scenario 2 while updating Source for resource https://id.openraadsinformatie.nl/2417366 with IRI https://openbesluitvorming.nl/voc/mapping/oss/ibabs/party/groenlinks-pvda

[View on Bugsnag](https://app.bugsnag.com/argu/ori/errors/5e4abfc58e0fcd001976de15?event_id=5e69640d0058321a3b5a0000&i=gh&m=ci)

## Stacktrace

    models/postgres_database.py:321 - update_source
    models/postgres_database.py:122 - save

[View full stacktrace](https://app.bugsnag.com/argu/ori/errors/5e4abfc58e0fcd001976de15?event_id=5e69640d0058321a3b5a0000&i=gh&m=ci)

*Created by Jurrian Tromp via Bugsnag*

**Comment by jorritb** [comment]
Most likely this is happening because the production `Source` table is still slightly contaminated from when we ran a wrong version of the code for a few days. It doesn't happen on a clean database.

The only solution I can think of is to try and create an SQL query that deletes any invalid entries in the `Source` table but that wouldn't be easy.

**Comment by jorritb** [comment]
@jurrian thoughts? The error has barely happened in the last 2 weeks so I would close this for now.

**Comment by jurrian** [comment]
Okay, we will close this for now until new problems are logged.
