### ISSUE TITLE
Duplicate ES indexes for municipalities (heumen, buren, hof twente)

### ISSUE THREAD

**Issue by joepio** [openstate/open-raadsinformatie#382]
e.g.: 

- ori_heumen_20200717161255
- ori_heumen_20200717161256

- ori_hofvantwente_20200717161511
- ori_hofvantwente_20200717161510

These seem to be created at the same moment.

Document count is the same in heumen:

<img width="299" alt="Screenshot 2020-09-17 at 10 02 45" src="https://user-images.githubusercontent.com/2183313/93438114-24f15000-f8cd-11ea-88d4-e1d9790a8a82.png">

But not in hof van twente:

<img width="289" alt="Screenshot 2020-09-17 at 10 04 37" src="https://user-images.githubusercontent.com/2183313/93438153-35092f80-f8cd-11ea-84c5-8547b3524170.png">

buren is split over two years, so might have a different cause.

- ori_buren_20190809125107
- ori_buren_20200206221649

Note that Buren uses iBabs, Heumen uses Notubiz and Hof van Twente uses GO.

**Comment by baksand** [comment]
this concerns more gemeenten so please check database

**Comment by jurrian** [comment]
I think this might have been caused by a race condition which does not happen often. Here Heumen has been processed by one processor and probably a second time by another processor which at that time could not find the index that was being created at that instance. I will delete the second index and run the import again for these municipalities just to be sure.

**Comment by jurrian** [comment]
The following duplicates have been deleted:
- Groningen
- Buren
- Doesburg
- Drechtsteden
- Heumen
- Hof van Twente
- Medemblik
