### ISSUE TITLE
Error retrieving results: "Network request failed" - Outdated cert

### ISSUE THREAD

**Issue by vanderburgt** [openstate/open-raadsinformatie#450]
## Describe the bug
**Summary**
When retrieving results on Openbesluitvorming.nl an error appears: "Network request failed". Possibly related to expired SSL certificate.

**URL / Environment**
https://openbesluitvorming.nl/

## Steps to reproduce
1. Go to https://openbesluitvorming.nl
2. Click on the organization select field and type: "Test"
3. See error: "Network request failed"

## Expected behavior
Results are shown

## Screenshots
<img width="1320" alt="Screenshot 2023-11-21 at 08 28 10" src="https://github.com/openstate/open-raadsinformatie/assets/8989205/0f80068f-4ad7-4089-85c4-624c20d301c9">

## Additional context
Firefox 119.0.1 / MacOS Sonoma

**Comment by joepio** [comment]
This is the HTTPS cert of the API that isn't functioning properly. Since this page is not hosted by Netlify (contrary to the front-end), we can't set HTTPS using Netlify. 

@breyten I'm assuming you're running something like nginx on the ORI API server, right? I suspect the cert there is outdated

**Comment by siccovansas** [comment]
This is the result of the nameserver change which caused the automatic renewal of certbot to no longer work as it uses TransIP DNS which assumes TransIP nameservers. We changed certbot to now use the HTTP method instead of the DNS method. We now have a valid certificate again. We also added certificate monitoring for this domain to detect issues in an earlier stage.
