### ISSUE TITLE
file_to_text task not executed

### ISSUE THREAD

**Issue by breyten** [openstate/open-raadsinformatie#54]
![image](https://user-images.githubusercontent.com/154791/33661202-213d8e36-da87-11e7-8f26-db12448f1602.png)

Leads to

![image](https://user-images.githubusercontent.com/154791/33661232-3a5f6a6a-da87-11e7-9c86-3eed518aadb5.png)

https://api.notubiz.nl/events/meetings/415545 seems to have valid documents though

**Comment by breyten** [comment]
This works with iBabs, by the way

**Comment by jurrian** [comment]
I see no documents in this meeting, there are only document in the submeetings. So since there are no meetings, the 'Document' download button in the Frontend shouldn't show.
Maybe the button shows because there is an item in the 'sources' array? If that is the case then something funny is going on since I originally copied it from [go_meetings](https://github.com/openstate/open-raadsinformatie/blob/c11169885b9287e0e2681bfa71a3640edda1e5c7/ocd_backend/items/go_meeting.py#L231), I assumed it was mandatory.

**Comment by breyten** [comment]
Ah, reading xml is hard :P  Ha, I see. I'm not sure anymore why it is in there, to be honest.

**Comment by breyten** [comment]
Moving this to https://github.com/openstate/ori-search/issues/4
